# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_noaa_swig', [dirname(__file__)])
        except ImportError:
            import _noaa_swig
            return _noaa_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_noaa_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _noaa_swig = swig_import_helper()
    del swig_import_helper
else:
    import _noaa_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def high_res_timer_now():
  """high_res_timer_now() -> gr::high_res_timer_type"""
  return _noaa_swig.high_res_timer_now()

def high_res_timer_now_perfmon():
  """high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
  return _noaa_swig.high_res_timer_now_perfmon()

def high_res_timer_tps():
  """high_res_timer_tps() -> gr::high_res_timer_type"""
  return _noaa_swig.high_res_timer_tps()

def high_res_timer_epoch():
  """high_res_timer_epoch() -> gr::high_res_timer_type"""
  return _noaa_swig.high_res_timer_epoch()
class hrpt_decoder(object):
    """
    NOAA HRPT Decoder.

    Constructor Specific Documentation:

    Make NOAA HRPT Decoder.

    Args:
        verbose : 
        output_files : 
    """
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make(*args, **kwargs):
        """
        make(bool verbose, bool output_files) -> hrpt_decoder_sptr

        NOAA HRPT Decoder.

        Constructor Specific Documentation:

        Make NOAA HRPT Decoder.

        Args:
            verbose : 
            output_files : 
        """
        return _noaa_swig.hrpt_decoder_make(*args, **kwargs)

    make = staticmethod(make)
    __swig_destroy__ = _noaa_swig.delete_hrpt_decoder
    __del__ = lambda self : None;
hrpt_decoder_swigregister = _noaa_swig.hrpt_decoder_swigregister
hrpt_decoder_swigregister(hrpt_decoder)

def hrpt_decoder_make(*args, **kwargs):
  """
    hrpt_decoder_make(bool verbose, bool output_files) -> hrpt_decoder_sptr

    NOAA HRPT Decoder.

    Constructor Specific Documentation:

    Make NOAA HRPT Decoder.

    Args:
        verbose : 
        output_files : 
    """
  return _noaa_swig.hrpt_decoder_make(*args, **kwargs)

class hrpt_deframer(object):
    """
    NOAA HRPT Deframer.

    Constructor Specific Documentation:

    Make NOAA HRPT Deframer.
    """
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make():
        """
        make() -> hrpt_deframer_sptr

        NOAA HRPT Deframer.

        Constructor Specific Documentation:

        Make NOAA HRPT Deframer.
        """
        return _noaa_swig.hrpt_deframer_make()

    make = staticmethod(make)
    __swig_destroy__ = _noaa_swig.delete_hrpt_deframer
    __del__ = lambda self : None;
hrpt_deframer_swigregister = _noaa_swig.hrpt_deframer_swigregister
hrpt_deframer_swigregister(hrpt_deframer)

def hrpt_deframer_make():
  """
    hrpt_deframer_make() -> hrpt_deframer_sptr

    NOAA HRPT Deframer.

    Constructor Specific Documentation:

    Make NOAA HRPT Deframer.
    """
  return _noaa_swig.hrpt_deframer_make()

class hrpt_pll_cf(object):
    """
    NOAA HRPT PLL.

    Constructor Specific Documentation:



    Args:
        alpha : 
        beta : 
        max_offset : 
    """
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def make(*args, **kwargs):
        """
        make(float alpha, float beta, float max_offset) -> hrpt_pll_cf_sptr

        NOAA HRPT PLL.

        Constructor Specific Documentation:



        Args:
            alpha : 
            beta : 
            max_offset : 
        """
        return _noaa_swig.hrpt_pll_cf_make(*args, **kwargs)

    make = staticmethod(make)
    def set_alpha(self, *args, **kwargs):
        """set_alpha(hrpt_pll_cf self, float alpha)"""
        return _noaa_swig.hrpt_pll_cf_set_alpha(self, *args, **kwargs)

    def set_beta(self, *args, **kwargs):
        """set_beta(hrpt_pll_cf self, float beta)"""
        return _noaa_swig.hrpt_pll_cf_set_beta(self, *args, **kwargs)

    def set_max_offset(self, *args, **kwargs):
        """set_max_offset(hrpt_pll_cf self, float max_offset)"""
        return _noaa_swig.hrpt_pll_cf_set_max_offset(self, *args, **kwargs)

    __swig_destroy__ = _noaa_swig.delete_hrpt_pll_cf
    __del__ = lambda self : None;
hrpt_pll_cf_swigregister = _noaa_swig.hrpt_pll_cf_swigregister
hrpt_pll_cf_swigregister(hrpt_pll_cf)

def hrpt_pll_cf_make(*args, **kwargs):
  """
    hrpt_pll_cf_make(float alpha, float beta, float max_offset) -> hrpt_pll_cf_sptr

    NOAA HRPT PLL.

    Constructor Specific Documentation:



    Args:
        alpha : 
        beta : 
        max_offset : 
    """
  return _noaa_swig.hrpt_pll_cf_make(*args, **kwargs)

class hrpt_decoder_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::noaa::hrpt_decoder)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::noaa::hrpt_decoder)> self) -> hrpt_decoder_sptr
        __init__(boost::shared_ptr<(gr::noaa::hrpt_decoder)> self, hrpt_decoder p) -> hrpt_decoder_sptr
        """
        this = _noaa_swig.new_hrpt_decoder_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(hrpt_decoder_sptr self) -> hrpt_decoder"""
        return _noaa_swig.hrpt_decoder_sptr___deref__(self)

    __swig_destroy__ = _noaa_swig.delete_hrpt_decoder_sptr
    __del__ = lambda self : None;
    def make(self, *args, **kwargs):
        """
        make(hrpt_decoder_sptr self, bool verbose, bool output_files) -> hrpt_decoder_sptr

        NOAA HRPT Decoder.

        Constructor Specific Documentation:

        Make NOAA HRPT Decoder.

        Args:
            verbose : 
            output_files : 
        """
        return _noaa_swig.hrpt_decoder_sptr_make(self, *args, **kwargs)

    def history(self):
        """history(hrpt_decoder_sptr self) -> unsigned int"""
        return _noaa_swig.hrpt_decoder_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(hrpt_decoder_sptr self, int which, int delay)
        declare_sample_delay(hrpt_decoder_sptr self, unsigned int delay)
        """
        return _noaa_swig.hrpt_decoder_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(hrpt_decoder_sptr self, int which) -> unsigned int"""
        return _noaa_swig.hrpt_decoder_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(hrpt_decoder_sptr self) -> int"""
        return _noaa_swig.hrpt_decoder_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(hrpt_decoder_sptr self) -> double"""
        return _noaa_swig.hrpt_decoder_sptr_relative_rate(self)

    def start(self):
        """start(hrpt_decoder_sptr self) -> bool"""
        return _noaa_swig.hrpt_decoder_sptr_start(self)

    def stop(self):
        """stop(hrpt_decoder_sptr self) -> bool"""
        return _noaa_swig.hrpt_decoder_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(hrpt_decoder_sptr self, unsigned int which_input) -> uint64_t"""
        return _noaa_swig.hrpt_decoder_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(hrpt_decoder_sptr self, unsigned int which_output) -> uint64_t"""
        return _noaa_swig.hrpt_decoder_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(hrpt_decoder_sptr self) -> int"""
        return _noaa_swig.hrpt_decoder_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(hrpt_decoder_sptr self, int m)"""
        return _noaa_swig.hrpt_decoder_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(hrpt_decoder_sptr self)"""
        return _noaa_swig.hrpt_decoder_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(hrpt_decoder_sptr self) -> bool"""
        return _noaa_swig.hrpt_decoder_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(hrpt_decoder_sptr self, int m)"""
        return _noaa_swig.hrpt_decoder_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(hrpt_decoder_sptr self) -> int"""
        return _noaa_swig.hrpt_decoder_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(hrpt_decoder_sptr self, int i) -> long"""
        return _noaa_swig.hrpt_decoder_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(hrpt_decoder_sptr self, long max_output_buffer)
        set_max_output_buffer(hrpt_decoder_sptr self, int port, long max_output_buffer)
        """
        return _noaa_swig.hrpt_decoder_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(hrpt_decoder_sptr self, int i) -> long"""
        return _noaa_swig.hrpt_decoder_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(hrpt_decoder_sptr self, long min_output_buffer)
        set_min_output_buffer(hrpt_decoder_sptr self, int port, long min_output_buffer)
        """
        return _noaa_swig.hrpt_decoder_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(hrpt_decoder_sptr self) -> float"""
        return _noaa_swig.hrpt_decoder_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(hrpt_decoder_sptr self) -> float"""
        return _noaa_swig.hrpt_decoder_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(hrpt_decoder_sptr self) -> float"""
        return _noaa_swig.hrpt_decoder_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(hrpt_decoder_sptr self) -> float"""
        return _noaa_swig.hrpt_decoder_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(hrpt_decoder_sptr self) -> float"""
        return _noaa_swig.hrpt_decoder_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(hrpt_decoder_sptr self) -> float"""
        return _noaa_swig.hrpt_decoder_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(hrpt_decoder_sptr self, int which) -> float
        pc_input_buffers_full(hrpt_decoder_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_decoder_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(hrpt_decoder_sptr self, int which) -> float
        pc_input_buffers_full_avg(hrpt_decoder_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_decoder_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(hrpt_decoder_sptr self, int which) -> float
        pc_input_buffers_full_var(hrpt_decoder_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_decoder_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(hrpt_decoder_sptr self, int which) -> float
        pc_output_buffers_full(hrpt_decoder_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_decoder_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(hrpt_decoder_sptr self, int which) -> float
        pc_output_buffers_full_avg(hrpt_decoder_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_decoder_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(hrpt_decoder_sptr self, int which) -> float
        pc_output_buffers_full_var(hrpt_decoder_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_decoder_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(hrpt_decoder_sptr self) -> float"""
        return _noaa_swig.hrpt_decoder_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(hrpt_decoder_sptr self) -> float"""
        return _noaa_swig.hrpt_decoder_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(hrpt_decoder_sptr self) -> float"""
        return _noaa_swig.hrpt_decoder_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(hrpt_decoder_sptr self) -> float"""
        return _noaa_swig.hrpt_decoder_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(hrpt_decoder_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _noaa_swig.hrpt_decoder_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(hrpt_decoder_sptr self)"""
        return _noaa_swig.hrpt_decoder_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(hrpt_decoder_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _noaa_swig.hrpt_decoder_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(hrpt_decoder_sptr self) -> int"""
        return _noaa_swig.hrpt_decoder_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(hrpt_decoder_sptr self) -> int"""
        return _noaa_swig.hrpt_decoder_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(hrpt_decoder_sptr self, int priority) -> int"""
        return _noaa_swig.hrpt_decoder_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(hrpt_decoder_sptr self) -> std::string"""
        return _noaa_swig.hrpt_decoder_sptr_name(self)

    def symbol_name(self):
        """symbol_name(hrpt_decoder_sptr self) -> std::string"""
        return _noaa_swig.hrpt_decoder_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(hrpt_decoder_sptr self) -> io_signature_sptr"""
        return _noaa_swig.hrpt_decoder_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(hrpt_decoder_sptr self) -> io_signature_sptr"""
        return _noaa_swig.hrpt_decoder_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(hrpt_decoder_sptr self) -> long"""
        return _noaa_swig.hrpt_decoder_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(hrpt_decoder_sptr self) -> basic_block_sptr"""
        return _noaa_swig.hrpt_decoder_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(hrpt_decoder_sptr self, int ninputs, int noutputs) -> bool"""
        return _noaa_swig.hrpt_decoder_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(hrpt_decoder_sptr self) -> std::string"""
        return _noaa_swig.hrpt_decoder_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(hrpt_decoder_sptr self, std::string name)"""
        return _noaa_swig.hrpt_decoder_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(hrpt_decoder_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _noaa_swig.hrpt_decoder_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(hrpt_decoder_sptr self) -> swig_int_ptr"""
        return _noaa_swig.hrpt_decoder_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(hrpt_decoder_sptr self) -> swig_int_ptr"""
        return _noaa_swig.hrpt_decoder_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(hrpt_decoder_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _noaa_swig.hrpt_decoder_sptr_message_subscribers(self, *args, **kwargs)

hrpt_decoder_sptr_swigregister = _noaa_swig.hrpt_decoder_sptr_swigregister
hrpt_decoder_sptr_swigregister(hrpt_decoder_sptr)

hrpt_decoder_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
hrpt_decoder = hrpt_decoder.make;

class hrpt_deframer_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::noaa::hrpt_deframer)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::noaa::hrpt_deframer)> self) -> hrpt_deframer_sptr
        __init__(boost::shared_ptr<(gr::noaa::hrpt_deframer)> self, hrpt_deframer p) -> hrpt_deframer_sptr
        """
        this = _noaa_swig.new_hrpt_deframer_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(hrpt_deframer_sptr self) -> hrpt_deframer"""
        return _noaa_swig.hrpt_deframer_sptr___deref__(self)

    __swig_destroy__ = _noaa_swig.delete_hrpt_deframer_sptr
    __del__ = lambda self : None;
    def make(self):
        """
        make(hrpt_deframer_sptr self) -> hrpt_deframer_sptr

        NOAA HRPT Deframer.

        Constructor Specific Documentation:

        Make NOAA HRPT Deframer.
        """
        return _noaa_swig.hrpt_deframer_sptr_make(self)

    def history(self):
        """history(hrpt_deframer_sptr self) -> unsigned int"""
        return _noaa_swig.hrpt_deframer_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(hrpt_deframer_sptr self, int which, int delay)
        declare_sample_delay(hrpt_deframer_sptr self, unsigned int delay)
        """
        return _noaa_swig.hrpt_deframer_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(hrpt_deframer_sptr self, int which) -> unsigned int"""
        return _noaa_swig.hrpt_deframer_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(hrpt_deframer_sptr self) -> int"""
        return _noaa_swig.hrpt_deframer_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(hrpt_deframer_sptr self) -> double"""
        return _noaa_swig.hrpt_deframer_sptr_relative_rate(self)

    def start(self):
        """start(hrpt_deframer_sptr self) -> bool"""
        return _noaa_swig.hrpt_deframer_sptr_start(self)

    def stop(self):
        """stop(hrpt_deframer_sptr self) -> bool"""
        return _noaa_swig.hrpt_deframer_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(hrpt_deframer_sptr self, unsigned int which_input) -> uint64_t"""
        return _noaa_swig.hrpt_deframer_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(hrpt_deframer_sptr self, unsigned int which_output) -> uint64_t"""
        return _noaa_swig.hrpt_deframer_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(hrpt_deframer_sptr self) -> int"""
        return _noaa_swig.hrpt_deframer_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(hrpt_deframer_sptr self, int m)"""
        return _noaa_swig.hrpt_deframer_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(hrpt_deframer_sptr self)"""
        return _noaa_swig.hrpt_deframer_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(hrpt_deframer_sptr self) -> bool"""
        return _noaa_swig.hrpt_deframer_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(hrpt_deframer_sptr self, int m)"""
        return _noaa_swig.hrpt_deframer_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(hrpt_deframer_sptr self) -> int"""
        return _noaa_swig.hrpt_deframer_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(hrpt_deframer_sptr self, int i) -> long"""
        return _noaa_swig.hrpt_deframer_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(hrpt_deframer_sptr self, long max_output_buffer)
        set_max_output_buffer(hrpt_deframer_sptr self, int port, long max_output_buffer)
        """
        return _noaa_swig.hrpt_deframer_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(hrpt_deframer_sptr self, int i) -> long"""
        return _noaa_swig.hrpt_deframer_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(hrpt_deframer_sptr self, long min_output_buffer)
        set_min_output_buffer(hrpt_deframer_sptr self, int port, long min_output_buffer)
        """
        return _noaa_swig.hrpt_deframer_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(hrpt_deframer_sptr self) -> float"""
        return _noaa_swig.hrpt_deframer_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(hrpt_deframer_sptr self) -> float"""
        return _noaa_swig.hrpt_deframer_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(hrpt_deframer_sptr self) -> float"""
        return _noaa_swig.hrpt_deframer_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(hrpt_deframer_sptr self) -> float"""
        return _noaa_swig.hrpt_deframer_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(hrpt_deframer_sptr self) -> float"""
        return _noaa_swig.hrpt_deframer_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(hrpt_deframer_sptr self) -> float"""
        return _noaa_swig.hrpt_deframer_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(hrpt_deframer_sptr self, int which) -> float
        pc_input_buffers_full(hrpt_deframer_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_deframer_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(hrpt_deframer_sptr self, int which) -> float
        pc_input_buffers_full_avg(hrpt_deframer_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_deframer_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(hrpt_deframer_sptr self, int which) -> float
        pc_input_buffers_full_var(hrpt_deframer_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_deframer_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(hrpt_deframer_sptr self, int which) -> float
        pc_output_buffers_full(hrpt_deframer_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_deframer_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(hrpt_deframer_sptr self, int which) -> float
        pc_output_buffers_full_avg(hrpt_deframer_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_deframer_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(hrpt_deframer_sptr self, int which) -> float
        pc_output_buffers_full_var(hrpt_deframer_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_deframer_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(hrpt_deframer_sptr self) -> float"""
        return _noaa_swig.hrpt_deframer_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(hrpt_deframer_sptr self) -> float"""
        return _noaa_swig.hrpt_deframer_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(hrpt_deframer_sptr self) -> float"""
        return _noaa_swig.hrpt_deframer_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(hrpt_deframer_sptr self) -> float"""
        return _noaa_swig.hrpt_deframer_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(hrpt_deframer_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _noaa_swig.hrpt_deframer_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(hrpt_deframer_sptr self)"""
        return _noaa_swig.hrpt_deframer_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(hrpt_deframer_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _noaa_swig.hrpt_deframer_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(hrpt_deframer_sptr self) -> int"""
        return _noaa_swig.hrpt_deframer_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(hrpt_deframer_sptr self) -> int"""
        return _noaa_swig.hrpt_deframer_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(hrpt_deframer_sptr self, int priority) -> int"""
        return _noaa_swig.hrpt_deframer_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(hrpt_deframer_sptr self) -> std::string"""
        return _noaa_swig.hrpt_deframer_sptr_name(self)

    def symbol_name(self):
        """symbol_name(hrpt_deframer_sptr self) -> std::string"""
        return _noaa_swig.hrpt_deframer_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(hrpt_deframer_sptr self) -> io_signature_sptr"""
        return _noaa_swig.hrpt_deframer_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(hrpt_deframer_sptr self) -> io_signature_sptr"""
        return _noaa_swig.hrpt_deframer_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(hrpt_deframer_sptr self) -> long"""
        return _noaa_swig.hrpt_deframer_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(hrpt_deframer_sptr self) -> basic_block_sptr"""
        return _noaa_swig.hrpt_deframer_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(hrpt_deframer_sptr self, int ninputs, int noutputs) -> bool"""
        return _noaa_swig.hrpt_deframer_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(hrpt_deframer_sptr self) -> std::string"""
        return _noaa_swig.hrpt_deframer_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(hrpt_deframer_sptr self, std::string name)"""
        return _noaa_swig.hrpt_deframer_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(hrpt_deframer_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _noaa_swig.hrpt_deframer_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(hrpt_deframer_sptr self) -> swig_int_ptr"""
        return _noaa_swig.hrpt_deframer_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(hrpt_deframer_sptr self) -> swig_int_ptr"""
        return _noaa_swig.hrpt_deframer_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(hrpt_deframer_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _noaa_swig.hrpt_deframer_sptr_message_subscribers(self, *args, **kwargs)

hrpt_deframer_sptr_swigregister = _noaa_swig.hrpt_deframer_sptr_swigregister
hrpt_deframer_sptr_swigregister(hrpt_deframer_sptr)

hrpt_deframer_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
hrpt_deframer = hrpt_deframer.make;

class hrpt_pll_cf_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::noaa::hrpt_pll_cf)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::noaa::hrpt_pll_cf)> self) -> hrpt_pll_cf_sptr
        __init__(boost::shared_ptr<(gr::noaa::hrpt_pll_cf)> self, hrpt_pll_cf p) -> hrpt_pll_cf_sptr
        """
        this = _noaa_swig.new_hrpt_pll_cf_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(hrpt_pll_cf_sptr self) -> hrpt_pll_cf"""
        return _noaa_swig.hrpt_pll_cf_sptr___deref__(self)

    __swig_destroy__ = _noaa_swig.delete_hrpt_pll_cf_sptr
    __del__ = lambda self : None;
    def make(self, *args, **kwargs):
        """
        make(hrpt_pll_cf_sptr self, float alpha, float beta, float max_offset) -> hrpt_pll_cf_sptr

        NOAA HRPT PLL.

        Constructor Specific Documentation:



        Args:
            alpha : 
            beta : 
            max_offset : 
        """
        return _noaa_swig.hrpt_pll_cf_sptr_make(self, *args, **kwargs)

    def set_alpha(self, *args, **kwargs):
        """set_alpha(hrpt_pll_cf_sptr self, float alpha)"""
        return _noaa_swig.hrpt_pll_cf_sptr_set_alpha(self, *args, **kwargs)

    def set_beta(self, *args, **kwargs):
        """set_beta(hrpt_pll_cf_sptr self, float beta)"""
        return _noaa_swig.hrpt_pll_cf_sptr_set_beta(self, *args, **kwargs)

    def set_max_offset(self, *args, **kwargs):
        """set_max_offset(hrpt_pll_cf_sptr self, float max_offset)"""
        return _noaa_swig.hrpt_pll_cf_sptr_set_max_offset(self, *args, **kwargs)

    def history(self):
        """history(hrpt_pll_cf_sptr self) -> unsigned int"""
        return _noaa_swig.hrpt_pll_cf_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(hrpt_pll_cf_sptr self, int which, int delay)
        declare_sample_delay(hrpt_pll_cf_sptr self, unsigned int delay)
        """
        return _noaa_swig.hrpt_pll_cf_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(hrpt_pll_cf_sptr self, int which) -> unsigned int"""
        return _noaa_swig.hrpt_pll_cf_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(hrpt_pll_cf_sptr self) -> int"""
        return _noaa_swig.hrpt_pll_cf_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(hrpt_pll_cf_sptr self) -> double"""
        return _noaa_swig.hrpt_pll_cf_sptr_relative_rate(self)

    def start(self):
        """start(hrpt_pll_cf_sptr self) -> bool"""
        return _noaa_swig.hrpt_pll_cf_sptr_start(self)

    def stop(self):
        """stop(hrpt_pll_cf_sptr self) -> bool"""
        return _noaa_swig.hrpt_pll_cf_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(hrpt_pll_cf_sptr self, unsigned int which_input) -> uint64_t"""
        return _noaa_swig.hrpt_pll_cf_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(hrpt_pll_cf_sptr self, unsigned int which_output) -> uint64_t"""
        return _noaa_swig.hrpt_pll_cf_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(hrpt_pll_cf_sptr self) -> int"""
        return _noaa_swig.hrpt_pll_cf_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(hrpt_pll_cf_sptr self, int m)"""
        return _noaa_swig.hrpt_pll_cf_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(hrpt_pll_cf_sptr self)"""
        return _noaa_swig.hrpt_pll_cf_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(hrpt_pll_cf_sptr self) -> bool"""
        return _noaa_swig.hrpt_pll_cf_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(hrpt_pll_cf_sptr self, int m)"""
        return _noaa_swig.hrpt_pll_cf_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(hrpt_pll_cf_sptr self) -> int"""
        return _noaa_swig.hrpt_pll_cf_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(hrpt_pll_cf_sptr self, int i) -> long"""
        return _noaa_swig.hrpt_pll_cf_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(hrpt_pll_cf_sptr self, long max_output_buffer)
        set_max_output_buffer(hrpt_pll_cf_sptr self, int port, long max_output_buffer)
        """
        return _noaa_swig.hrpt_pll_cf_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(hrpt_pll_cf_sptr self, int i) -> long"""
        return _noaa_swig.hrpt_pll_cf_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(hrpt_pll_cf_sptr self, long min_output_buffer)
        set_min_output_buffer(hrpt_pll_cf_sptr self, int port, long min_output_buffer)
        """
        return _noaa_swig.hrpt_pll_cf_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(hrpt_pll_cf_sptr self) -> float"""
        return _noaa_swig.hrpt_pll_cf_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(hrpt_pll_cf_sptr self) -> float"""
        return _noaa_swig.hrpt_pll_cf_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(hrpt_pll_cf_sptr self) -> float"""
        return _noaa_swig.hrpt_pll_cf_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(hrpt_pll_cf_sptr self) -> float"""
        return _noaa_swig.hrpt_pll_cf_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(hrpt_pll_cf_sptr self) -> float"""
        return _noaa_swig.hrpt_pll_cf_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(hrpt_pll_cf_sptr self) -> float"""
        return _noaa_swig.hrpt_pll_cf_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(hrpt_pll_cf_sptr self, int which) -> float
        pc_input_buffers_full(hrpt_pll_cf_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_pll_cf_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(hrpt_pll_cf_sptr self, int which) -> float
        pc_input_buffers_full_avg(hrpt_pll_cf_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_pll_cf_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(hrpt_pll_cf_sptr self, int which) -> float
        pc_input_buffers_full_var(hrpt_pll_cf_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_pll_cf_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(hrpt_pll_cf_sptr self, int which) -> float
        pc_output_buffers_full(hrpt_pll_cf_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_pll_cf_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(hrpt_pll_cf_sptr self, int which) -> float
        pc_output_buffers_full_avg(hrpt_pll_cf_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_pll_cf_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(hrpt_pll_cf_sptr self, int which) -> float
        pc_output_buffers_full_var(hrpt_pll_cf_sptr self) -> pmt_vector_float
        """
        return _noaa_swig.hrpt_pll_cf_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(hrpt_pll_cf_sptr self) -> float"""
        return _noaa_swig.hrpt_pll_cf_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(hrpt_pll_cf_sptr self) -> float"""
        return _noaa_swig.hrpt_pll_cf_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(hrpt_pll_cf_sptr self) -> float"""
        return _noaa_swig.hrpt_pll_cf_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(hrpt_pll_cf_sptr self) -> float"""
        return _noaa_swig.hrpt_pll_cf_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(hrpt_pll_cf_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _noaa_swig.hrpt_pll_cf_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(hrpt_pll_cf_sptr self)"""
        return _noaa_swig.hrpt_pll_cf_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(hrpt_pll_cf_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _noaa_swig.hrpt_pll_cf_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(hrpt_pll_cf_sptr self) -> int"""
        return _noaa_swig.hrpt_pll_cf_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(hrpt_pll_cf_sptr self) -> int"""
        return _noaa_swig.hrpt_pll_cf_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(hrpt_pll_cf_sptr self, int priority) -> int"""
        return _noaa_swig.hrpt_pll_cf_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(hrpt_pll_cf_sptr self) -> std::string"""
        return _noaa_swig.hrpt_pll_cf_sptr_name(self)

    def symbol_name(self):
        """symbol_name(hrpt_pll_cf_sptr self) -> std::string"""
        return _noaa_swig.hrpt_pll_cf_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(hrpt_pll_cf_sptr self) -> io_signature_sptr"""
        return _noaa_swig.hrpt_pll_cf_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(hrpt_pll_cf_sptr self) -> io_signature_sptr"""
        return _noaa_swig.hrpt_pll_cf_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(hrpt_pll_cf_sptr self) -> long"""
        return _noaa_swig.hrpt_pll_cf_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(hrpt_pll_cf_sptr self) -> basic_block_sptr"""
        return _noaa_swig.hrpt_pll_cf_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(hrpt_pll_cf_sptr self, int ninputs, int noutputs) -> bool"""
        return _noaa_swig.hrpt_pll_cf_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(hrpt_pll_cf_sptr self) -> std::string"""
        return _noaa_swig.hrpt_pll_cf_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(hrpt_pll_cf_sptr self, std::string name)"""
        return _noaa_swig.hrpt_pll_cf_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(hrpt_pll_cf_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _noaa_swig.hrpt_pll_cf_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(hrpt_pll_cf_sptr self) -> swig_int_ptr"""
        return _noaa_swig.hrpt_pll_cf_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(hrpt_pll_cf_sptr self) -> swig_int_ptr"""
        return _noaa_swig.hrpt_pll_cf_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(hrpt_pll_cf_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _noaa_swig.hrpt_pll_cf_sptr_message_subscribers(self, *args, **kwargs)

hrpt_pll_cf_sptr_swigregister = _noaa_swig.hrpt_pll_cf_sptr_swigregister
hrpt_pll_cf_sptr_swigregister(hrpt_pll_cf_sptr)

hrpt_pll_cf_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
hrpt_pll_cf = hrpt_pll_cf.make;



